apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appset.yaml

# Common labels for the ApplicationSet
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: argocd-example-apps
