apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-prod

resources:
  - ../../base

images:
  - name: gcr.io/google-samples/gb-frontend
    newTag: v4

patches:
  - target:
      kind: Namespace
      name: guestbook
    patch: |-
      - op: replace
        path: /metadata/name
        value: guestbook-prod
